#pragma once
#include QMK_KEYBOARD_H


enum custom_keycodes {
  ST_MACRO_0 = ML_SAFE_RANGE,
  ST_MACRO_1,
  ST_MACRO_2,
  ST_MACRO_3,
  ST_MACRO_4,
  ST_MACRO_5,
  ST_MACRO_6,
  ST_MACRO_7,
  ST_MACRO_8,
  ST_MACRO_9,
  ST_MACRO_10,
  ST_MACRO_11,
  ST_MACRO_12,
  ST_MACRO_13,
  ST_MACRO_14,
  ST_MACRO_15,
  ST_MACRO_16,
  ST_MACRO_17,
  ST_MACRO_18,
  ST_MACRO_19,
  ST_MACRO_20,
  ST_MACRO_21,
  ST_MACRO_22,
  ST_MACRO_23,
  ST_MACRO_24,
  ST_MACRO_25,
  ST_MACRO_26,
  ST_MACRO_27,
  ST_MACRO_28,
  ST_MACRO_29,
  ST_MACRO_30,
  ST_MACRO_31,
  ST_MACRO_32,
  ST_MACRO_33,
  ST_MACRO_34,
  ST_MACRO_35,
  ST_MACRO_36,
  ST_MACRO_37,
  ST_MACRO_38,
  ST_MACRO_39,
  ST_MACRO_40,
  ST_MACRO_41,
  ST_MACRO_42,
  ST_MACRO_43,
  ST_MACRO_44,
  ST_MACRO_45,
  ST_MACRO_46,
  ST_MACRO_47,
  ST_MACRO_48,
  ST_MACRO_49,
  ST_MACRO_50,
  ST_MACRO_51,
  ST_MACRO_52,
  ST_MACRO_53,
  ST_MACRO_54,
  ST_MACRO_55,
  ST_MACRO_56,
  ST_MACRO_57,
  ST_MACRO_58,
  ST_MACRO_59,
  ST_MACRO_60,
  ST_MACRO_61,
  ST_MACRO_62,
  ST_MACRO_63,
  ST_MACRO_64,
  ST_MACRO_65,
  ST_MACRO_66,
  ST_MACRO_67,
  ST_MACRO_68,
  ST_MACRO_69,
  ST_MACRO_70,
  ST_MACRO_71,
  ST_MACRO_72,

  CKC_SPACE,
  CKC_ENTER,
  CKC_ESC,
  CKC_TAB,
  CKC_LANG,

  CKC_A,
  CKC_S,
  CKC_D,
  CKC_F,
  CKC_G,

  CKC_H,
  CKC_J,
  CKC_K,
  CKC_L,
  CKC_SEMICOLON,

  CKC_RU_A,
  CKC_RU_S,
  CKC_RU_D,
  CKC_RU_F,
  CKC_RU_G,

  CKC_RU_H,
  CKC_RU_J,
  CKC_RU_K,
  CKC_RU_L,
  CKC_RU_SEMICOLON,

  CKC_RU_U_A,
  CKC_RU_U_S,
  CKC_RU_U_D,
  CKC_RU_U_F,
  CKC_RU_U_G,

  CKC_RU_U_H,
  CKC_RU_U_J,
  CKC_RU_U_K,
  CKC_RU_U_L,

  MACRO_TO_SEMICOLON,
  MACRO_TO_COLON,
  MACRO_TO_BSLASH,
  MACRO_SLSH_OR_COLON,

  CKC_KP_DOT,
  CKC_KP_4,
  CKC_KP_5,
  CKC_KP_6,
  CKC_LPRN_L,
  CKC_LABK,
  CKC_LCBR,
  CKC_LPRN_R,
  CKC_LBRACKET,
  CKC_DQUO,

  CKC_F4,
  CKC_F5,
  CKC_F6,
  CKC_F11,
  CKC_LEFT,
  CKC_DOWN,
  CKC_UP,
  CKC_RIGHT,
  CKC_MEDIA_PREV_TRACK,
};


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [0] = LAYOUT_voyager(
    KC_TRANSPARENT, KC_Q,           KC_W,           KC_E,           KC_R,           KC_T,                                           KC_Y,           KC_U,           KC_I,           KC_O,           KC_P,           KC_TRANSPARENT,
    KC_BSPACE,      CKC_A,         CKC_S,          CKC_D,          CKC_F,          CKC_G,                                          CKC_H,          CKC_J,          CKC_K,          CKC_L,           CKC_SEMICOLON,   KC_TRANSPARENT,
    CKC_LANG,       KC_Z,           KC_X,           KC_C,           KC_V,           KC_B,                                           KC_N,           KC_M,           KC_HASH,    MACRO_TO_COLON,  MACRO_TO_SEMICOLON, KC_TRANSPARENT,
    KC_TRANSPARENT, KC_KP_SLASH,    KC_KP_ASTERISK, KC_KP_PLUS,     KC_KP_EQUAL,    KC_TAB,                                         KC_TRANSPARENT, KC_MINUS,       KC_AT,          KC_EXLM,        KC_QUES,        KC_TRANSPARENT,
                                                    CKC_SPACE,  CKC_ENTER,                                 CKC_ESC, CKC_TAB
  ),
  [1] = LAYOUT_voyager(
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,
    KC_TRANSPARENT, MACRO_TO_BSLASH,      KC_NO,          KC_NO,          KC_UNDS,        KC_TRANSPARENT,                                 KC_TRANSPARENT, ST_MACRO_0,     KC_HASH,    MACRO_TO_COLON,  MACRO_TO_SEMICOLON,      KC_TRANSPARENT,
                                                    KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT
  ),
  [2] = LAYOUT_voyager(
    KC_TRANSPARENT, ST_MACRO_1,     ST_MACRO_2,     ST_MACRO_3,     ST_MACRO_4,     ST_MACRO_5,                                     ST_MACRO_16,    ST_MACRO_17,    ST_MACRO_18,    ST_MACRO_19,    ST_MACRO_20,    ST_MACRO_21,
    KC_TRANSPARENT,   CKC_RU_A,       CKC_RU_S,      CKC_RU_D,        CKC_RU_F,        CKC_RU_G,                                       CKC_RU_H,       CKC_RU_J,       CKC_RU_K,       CKC_RU_L,   CKC_RU_SEMICOLON, ST_MACRO_26,
    CKC_LANG,          ST_MACRO_11,    ST_MACRO_12,    ST_MACRO_13,    ST_MACRO_14,    ST_MACRO_15,                                    ST_MACRO_27,    ST_MACRO_28,    ST_MACRO_29,    ST_MACRO_30,    ST_MACRO_31,    ST_MACRO_32,
    KC_TRANSPARENT, KC_KP_SLASH,    KC_KP_ASTERISK, KC_KP_PLUS,     KC_KP_EQUAL,    KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_MINUS,       KC_AT,          KC_EXLM,        KC_QUES,        KC_TRANSPARENT,
                                                    KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT
  ),
  [3] = LAYOUT_voyager(
    KC_TRANSPARENT, ST_MACRO_33,    ST_MACRO_34,    ST_MACRO_35,    ST_MACRO_36,    ST_MACRO_37,                                    ST_MACRO_48,    ST_MACRO_49,    ST_MACRO_50,    ST_MACRO_51,    ST_MACRO_52,    ST_MACRO_53,
    KC_TRANSPARENT,   CKC_RU_U_A,       CKC_RU_U_S,   CKC_RU_U_D,     CKC_RU_U_F,      CKC_RU_U_G,                                 CKC_RU_U_H,       CKC_RU_U_J,       CKC_RU_U_K,     CKC_RU_U_L,  CKC_RU_SEMICOLON, ST_MACRO_58,
    KC_TRANSPARENT, ST_MACRO_43,    ST_MACRO_44,    ST_MACRO_45,    ST_MACRO_46,    ST_MACRO_47,                                    ST_MACRO_59,    ST_MACRO_60,    ST_MACRO_61,    ST_MACRO_62,    ST_MACRO_63,    ST_MACRO_64,
    KC_TRANSPARENT, MACRO_TO_BSLASH,      KC_NO,          KC_NO,          KC_UNDS,        KC_TRANSPARENT,                                 KC_TRANSPARENT, ST_MACRO_65,    KC_HASH,        MACRO_TO_COLON,        MACRO_TO_SEMICOLON,      KC_TRANSPARENT,
                                                    KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT
  ),
  [4] = LAYOUT_voyager(
    KC_TRANSPARENT, KC_PERC,        KC_KP_7,        KC_KP_8,        KC_KP_9,        KC_RPRN,                                        KC_RABK,        KC_RCBR,        KC_RPRN,        KC_RBRACKET,    KC_QUOTE,       KC_DLR,
    KC_TRANSPARENT, CKC_KP_DOT,     CKC_KP_4,       CKC_KP_5,       CKC_KP_6,       CKC_LPRN_L,                                     CKC_LABK, CKC_LCBR , CKC_LPRN_R,  CKC_LBRACKET, CKC_DQUO,    ST_MACRO_66,
    KC_TRANSPARENT, KC_KP_0,        KC_KP_1,        KC_KP_2,        KC_KP_3,        KC_KP_MINUS,                                    KC_CIRC,        KC_AMPR,        KC_PIPE,        KC_TILD,        KC_GRAVE,       ST_MACRO_67,
    KC_TRANSPARENT, MACRO_SLSH_OR_COLON,    KC_KP_ASTERISK, KC_KP_PLUS,     KC_KP_EQUAL,    KC_TRANSPARENT,                                 ST_MACRO_68,    ST_MACRO_69,    ST_MACRO_70,    ST_MACRO_71,    KC_NO,          KC_TRANSPARENT,
                                                    KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT
  ),
  [5] = LAYOUT_voyager(
    KC_TRANSPARENT, ST_MACRO_72,    KC_F7,          KC_F8,          KC_F9,          KC_F10,                                         KC_BRIGHTNESS_DOWN,KC_BRIGHTNESS_UP,KC_AUDIO_VOL_DOWN,KC_AUDIO_VOL_UP,KC_MEDIA_NEXT_TRACK,KC_TRANSPARENT,
    KC_TRANSPARENT, KC_LGUI,        CKC_F4,  CKC_F5, CKC_F6,  CKC_F11,                                CKC_LEFT, CKC_DOWN, CKC_UP, CKC_RIGHT, CKC_MEDIA_PREV_TRACK, KC_TRANSPARENT,
    KC_TRANSPARENT, KC_TRANSPARENT, KC_F1,          KC_F2,          KC_F3,          KC_F12,                                         KC_HOME,        KC_PGDOWN,      KC_PGUP,        KC_END,         KC_MEDIA_PLAY_PAUSE,KC_TRANSPARENT,
    KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,
                                                    KC_TRANSPARENT, KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_TRANSPARENT
  ),
};
